# Generated by Django 5.0.6 on 2024-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('languages_used', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
            ],
        ),
    ]
