# Generated by Django 5.0.6 on 2024-06-26 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('headshot', models.ImageField(upload_to='temp/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('cname', models.CharField(max_length=80)),
                ('c_credits', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('createdon', models.DateField(default=datetime.date(2024, 6, 26), null=True)),
                ('month', models.DateField(default=datetime.date(2024, 6, 26), null=True)),
                ('enrollment', models.ManyToManyField(to='couresRegistration.students')),
            ],
        ),
    ]
